In [4]:
number <- "Three"
suit <- "Hearts"
paste(number, suit) # Using paste on string

[1] "Three Hearts"

In [5]:
paste(letters[1:5], as.character(1:5)) # Using paste on vectors

[1] "a 1" "b 2" "c 3" "d 4" "e 5"

In [6]:
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [7]:
expand.grid(pants=c("blue", "black"), shirt = c("white", "grey", "plaid")) # Gives all possible combinations

pants shirt
1 blue  white
2 black white
3 blue  grey 
4 black grey 
5 blue  plaid
6 black plaid

## Generating the deck of cards

In [13]:
suits <- c("Diamonds", "Clubs", "Hearts", "Spades")
numbers <- c("Ace", "Deuce", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Jack", "Queen", "King")
deck <- expand.grid(number=numbers, suits=suits)
head(deck)

number suits   
1 Ace    Diamonds
2 Deuce  Diamonds
3 Three  Diamonds
4 Four   Diamonds
5 Five   Diamonds
6 Six    Diamonds

In [14]:
deck <- paste(deck$number, deck$suit)
deck

[1] "Ace Diamonds"   "Deuce Diamonds" "Three Diamonds" "Four Diamonds" 
 [5] "Five Diamonds"  "Six Diamonds"   "Seven Diamonds" "Eight Diamonds"
 [9] "Nine Diamonds"  "Ten Diamonds"   "Jack Diamonds"  "Queen Diamonds"
[13] "King Diamonds"  "Ace Clubs"      "Deuce Clubs"    "Three Clubs"   
[17] "Four Clubs"     "Five Clubs"     "Six Clubs"      "Seven Clubs"   
[21] "Eight Clubs"    "Nine Clubs"     "Ten Clubs"      "Jack Clubs"    
[25] "Queen Clubs"    "King Clubs"     "Ace Hearts"     "Deuce Hearts"  
[29] "Three Hearts"   "Four Hearts"    "Five Hearts"    "Six Hearts"    
[33] "Seven Hearts"   "Eight Hearts"   "Nine Hearts"    "Ten Hearts"    
[37] "Jack Hearts"    "Queen Hearts"   "King Hearts"    "Ace Spades"    
[41] "Deuce Spades"   "Three Spades"   "Four Spades"    "Five Spades"   
[45] "Six Spades"     "Seven Spades"   "Eight Spades"   "Nine Spades"   
[49] "Ten Spades"     "Jack Spades"    "Queen Spades"   "King Spades"

In [15]:
length(deck)

[1] 52

### Possible ways to select a king

In [32]:
kings <- paste("King", suits)
kings

[1] "King Diamonds" "King Clubs"    "King Hearts"   "King Spades"

In [18]:
mean(deck %in% kings) #What proportion of deck is 'kings'

[1] 0.07692308

## Using PnC from 'gtools' to select according to conditional probability

In [20]:
library(gtools)

In [22]:
permutations(5,2) # Arranging 5 numbers (1 to 5) into 2 spaces, these are the results:

[,1] [,2]
 [1,] 1    2   
 [2,] 1    3   
 [3,] 1    4   
 [4,] 1    5   
 [5,] 2    1   
 [6,] 2    3   
 [7,] 2    4   
 [8,] 2    5   
 [9,] 3    1   
[10,] 3    2   
[11,] 3    4   
[12,] 3    5   
[13,] 4    1   
[14,] 4    2   
[15,] 4    3   
[16,] 4    5   
[17,] 5    1   
[18,] 5    2   
[19,] 5    3   
[20,] 5    4

#### Generating phone numbers

In [23]:
all_phone_numbers <- permutations(10, 7, v=0:9) # Providing custom vector to use as source values to fit

In [24]:
n <- nrow(all_phone_numbers)
index <- sample(n, 5)
index # Selecting 5 random indexes

[1]  88383 122350 517692 184976 227481

In [25]:
all_phone_numbers[index,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    5    2    3    7    0    8   
[2,] 2    0    3    7    6    5    4   
[3,] 8    5    0    3    1    6    9   
[4,] 3    0    6    2    5    8    9   
[5,] 3    7    8    6    5    0    1

### Selecting 2 cards where order matters (R version of multiplation rule) : CONDITIONAL PROBABILITY

\begin{align}
Pr(B|A) = \frac{Pr(A and B)}{Pr(A)}\\
\end{align}

In [27]:
hands <- permutations(52, 2, v=dec)

In [30]:
head(hands)

[,1]      [,2]          
[1,] Ace Clubs Ace Diamonds  
[2,] Ace Clubs Ace Hearts    
[3,] Ace Clubs Ace Spades    
[4,] Ace Clubs Deuce Clubs   
[5,] Ace Clubs Deuce Diamonds
[6,] Ace Clubs Deuce Hearts

In [38]:
length(hands)

[1] 5304

In [39]:
first_card <- hands[,1]
second_card <- hands[,2]

In [43]:
first_card_king = sum(first_card %in% kings) # Checking first card is a king
first_card_king

[1] 204

In [45]:
# Checking if first and second card both are kings
both_first_and_second_king = sum(first_card %in% kings & second_card %in% kings)
both_first_and_second_king

[1] 12

In [46]:
# What proportion of 'first_card_king' is 'both_first_and_second_king' gives the conditional probability
both_first_and_second_king/first_card_king

[1] 0.05882353

## Generating combinations to win blackjack

In [48]:
aces <- paste("Ace", suits)

In [53]:
facecard <- c("King", "Queen", "Jack", "Ten")
facecard <- expand.grid(number=facecard, suit=suits)
facecard

number suit    
1  King   Diamonds
2  Queen  Diamonds
3  Jack   Diamonds
4  Ten    Diamonds
5  King   Clubs   
6  Queen  Clubs   
7  Jack   Clubs   
8  Ten    Clubs   
9  King   Hearts  
10 Queen  Hearts  
11 Jack   Hearts  
12 Ten    Hearts  
13 King   Spades  
14 Queen  Spades  
15 Jack   Spades  
16 Ten    Spades

In [54]:
facecard <- paste(facecard$number, facecard$suit)
facecard

[1] "King Diamonds"  "Queen Diamonds" "Jack Diamonds"  "Ten Diamonds"  
 [5] "King Clubs"     "Queen Clubs"    "Jack Clubs"     "Ten Clubs"     
 [9] "King Hearts"    "Queen Hearts"   "Jack Hearts"    "Ten Hearts"    
[13] "King Spades"    "Queen Spades"   "Jack Spades"    "Ten Spades"

In [56]:
hands <- combinations(52, 2, v=deck)
head(hands)

[,1]      [,2]          
[1,] Ace Clubs Ace Diamonds  
[2,] Ace Clubs Ace Hearts    
[3,] Ace Clubs Ace Spades    
[4,] Ace Clubs Deuce Clubs   
[5,] Ace Clubs Deuce Diamonds
[6,] Ace Clubs Deuce Hearts

In [65]:
# Counting how many times we get aces and facecard, since we calculated combinations, if ace-king appeared first, king-ace will not appear again.
mean(hands[,1] %in% aces & hands[,2] %in% facecard) # Counting aces in 1st column since it will appear first and king-ace won't appear because it's combination, not permumation

[1] 0.04826546

In [68]:
# To be safe, we will get the answer from both orders possible and keep the non zero one
mean((hands[,1] %in% aces & hands[,2] %in% facecard) | mean(hands[,2] %in% aces & hands[,1] %in% facecard))

[1] 0.04826546

### Approximating above stuff using Monte carlo method